export const Genres = [
  { value: 'ALL', viewValue: 'All' },
  { value: 'Art & Design', viewValue: 'Art & Design' },
  {
    value: 'Art & Design;Pretend Play',
    viewValue: 'Art & Design;Pretend Play',
  },
  { value: 'Art & Design;Creativity', viewValue: 'Art & Design;Creativity' },
  {
    value: 'Art & Design;Action & Adventure',
    viewValue: 'Art & Design;Action & Adventure',
  },
  { value: 'Auto & Vehicles', viewValue: 'Auto & Vehicles' },
  { value: 'Beauty', viewValue: 'Beauty' },
  { value: 'Books & Reference', viewValue: 'Books & Reference' },
  { value: 'Business', viewValue: 'Business' },
  { value: 'Comics', viewValue: 'Comics' },
  { value: 'Comics;Creativity', viewValue: 'Comics;Creativity' },
  { value: 'Communication', viewValue: 'Communication' },
  { value: 'Dating', viewValue: 'Dating' },
  { value: 'Education;Education', viewValue: 'Education;Education' },
  { value: 'Education', viewValue: 'Education' },
  { value: 'Education;Creativity', viewValue: 'Education;Creativity' },
  { value: 'Education;Music & Video', viewValue: 'Education;Music & Video' },
  {
    value: 'Education;Action & Adventure',
    viewValue: 'Education;Action & Adventure',
  },
  { value: 'Education;Pretend Play', viewValue: 'Education;Pretend Play' },
  { value: 'Education;Brain Games', viewValue: 'Education;Brain Games' },
  { value: 'Entertainment', viewValue: 'Entertainment' },
  {
    value: 'Entertainment;Music & Video',
    viewValue: 'Entertainment;Music & Video',
  },
  {
    value: 'Entertainment;Brain Games',
    viewValue: 'Entertainment;Brain Games',
  },
  { value: 'Entertainment;Creativity', viewValue: 'Entertainment;Creativity' },
  { value: 'Events', viewValue: 'Events' },
  { value: 'Finance', viewValue: 'Finance' },
  { value: 'Food & Drink', viewValue: 'Food & Drink' },
  { value: 'Health & Fitness', viewValue: 'Health & Fitness' },
  { value: 'House & Home', viewValue: 'House & Home' },
  { value: 'Libraries & Demo', viewValue: 'Libraries & Demo' },
  { value: 'Lifestyle', viewValue: 'Lifestyle' },
  { value: 'Lifestyle;Pretend Play', viewValue: 'Lifestyle;Pretend Play' },
  {
    value: 'Adventure;Action & Adventure',
    viewValue: 'Adventure;Action & Adventure',
  },
  { value: 'Arcade', viewValue: 'Arcade' },
  { value: 'Casual', viewValue: 'Casual' },
  { value: 'Card', viewValue: 'Card' },
  { value: 'Casual;Pretend Play', viewValue: 'Casual;Pretend Play' },
  { value: 'Action', viewValue: 'Action' },
  { value: 'Strategy', viewValue: 'Strategy' },
  { value: 'Puzzle', viewValue: 'Puzzle' },
  { value: 'Sports', viewValue: 'Sports' },
  { value: 'Music', viewValue: 'Music' },
  { value: 'Word', viewValue: 'Word' },
  { value: 'Racing', viewValue: 'Racing' },
  { value: 'Casual;Creativity', viewValue: 'Casual;Creativity' },
  {
    value: 'Casual;Action & Adventure',
    viewValue: 'Casual;Action & Adventure',
  },
  { value: 'Simulation', viewValue: 'Simulation' },
  { value: 'Adventure', viewValue: 'Adventure' },
  { value: 'Board', viewValue: 'Board' },
  { value: 'Trivia', viewValue: 'Trivia' },
  { value: 'Role Playing', viewValue: 'Role Playing' },
  { value: 'Simulation;Education', viewValue: 'Simulation;Education' },
  {
    value: 'Action;Action & Adventure',
    viewValue: 'Action;Action & Adventure',
  },
  { value: 'Casual;Brain Games', viewValue: 'Casual;Brain Games' },
  {
    value: 'Simulation;Action & Adventure',
    viewValue: 'Simulation;Action & Adventure',
  },
  { value: 'Educational;Creativity', viewValue: 'Educational;Creativity' },
  { value: 'Puzzle;Brain Games', viewValue: 'Puzzle;Brain Games' },
  { value: 'Educational;Education', viewValue: 'Educational;Education' },
];
