export const filter = [
  { column_name: 'track_name', label: 'Name', filter_type: 'Input' },
  { column_name: 'price', label: 'Price', filter_type: 'Slider' },
  {
    column_name: 'price',
    label: 'Type',
    filter_type: 'Radio',
    value: ['Free', 'Paid'],
  },
  {
    column_name: 'user_rating',
    label: 'Rating',
    filter_type: 'Radio',
    value: ['0 - 0.9', '1.0 - 1.9', '2.0 - 2.9', '3.0 - 3.9', '4.0 - 5.0'],
  },
  {
    column_name: 'prime_genre',
    label: 'Genre',
    filter_type: 'Select',
    value: [
      'Games',
      'Productivity',
      'Weather',
      'Shopping',
      'Reference',
      'Finance',
      'Music',
      'Utilities',
      'Travel',
      'Social Networking',
      'Sports',
      'Business',
      'Health & Fitness',
      'Entertainment',
      'Photo & Video',
      'Navigation',
      'Education',
      'Lifestyle',
      'Food & Drink',
      'News',
      'Book',
      'Medical',
      'Catalogs',
    ],
  },
];
