export const Categories = [
  { value: 'ALL', viewValue: 'All' },
  { value: 'ART_AND_DESIGN', viewValue: 'Art and Design' },
  { value: 'AUTO_AND_VEHICLES', viewValue: 'Auto and Vehicles' },
  { value: 'BEAUTY', viewValue: 'Beauty' },
  { value: 'BOOKS_AND_REFERENCE', viewValue: 'Books and Reference' },
  { value: 'BUSINESS', viewValue: 'Business' },
  { value: 'COMICS', viewValue: 'Comics' },
  { value: 'COMMUNICATION', viewValue: 'Communication' },
  { value: 'DATING', viewValue: 'Dating' },
  { value: 'EDUCATION', viewValue: 'Education' },
  { value: 'ENTERTAINMENT', viewValue: 'Entertainment' },
  { value: 'FINANCE', viewValue: 'Finance' },
  { value: 'FOOD_AND_DRINK', viewValue: 'Food and Drink' },
  { value: 'HEALTH_AND_FITNESS', viewValue: 'Health and Fitness' },
  { value: 'HOUSE_AND_HOME', viewValue: 'House and Home' },
  { value: 'LIBRARIES_AND_DEMO', viewValue: 'Libraries and Demo' },
  { value: 'LIFESTYLE', viewValue: 'Lifestyle' },
  { value: 'GAME', viewValue: 'Game' },
  { value: 'FAMILY', viewValue: 'Family' },
  { value: 'MEDICAL', viewValue: 'Medical' },
  { value: 'SOCIAL', viewValue: 'Social' },
  { value: 'SHOPPING', viewValue: 'Shopping' },
  { value: 'PHOTOGRAPHY', viewValue: 'Photography' },
  { value: 'SPORTS', viewValue: 'Sports' },
  { value: 'TRAVEL_AND_LOCAL', viewValue: 'Travel and Local' },
  { value: 'TOOL', viewValue: 'Tool' },
  { value: 'PERSONALIZATION', viewValue: 'Personalization' },
  { value: 'PRODUCTIVITY', viewValue: 'Productivity' },
  { value: 'PARENTING', viewValue: 'Parenting' },
  { value: 'WEATHER', viewValue: 'Weather' },
  { value: 'VIDEO_PLAYERS', viewValue: 'Video Players' },
  { value: 'NEWS_AND_MAGAZINES', viewValue: 'News and Magazines' },
  { value: 'MAPS_AND_NAVIGATION', viewValue: 'Maps and Navigation' },
];
