export const filter = [
  {
    column_name: 'Category',
    label: 'Category',
    filter_type: 'Select',
    value: [
        'ALL',
        'ART_AND_DESIGN',
        'AUTO_AND_VEHICLES',
        'BEAUTY',
        'BOOKS_AND_REFERENCE',
        'BUSINESS',
        'COMICS',
        'COMMUNICATION',
        'DATING',
        'EDUCATION',
        'ENTERTAINMENT',
        'FINANCE',
        'FOOD_AND_DRINK',
        'HEALTH_AND_FITNESS',
        'HOUSE_AND_HOME',
        'LIBRARIES_AND_DEMO',
        'LIFESTYLE',
        'GAME',
        'FAMILY',
        'MEDICAL',
        'SOCIAL',
        'SHOPPING',
        'PHOTOGRAPHY',
        'SPORTS',
        'TRAVEL_AND_LOCAL',
        'TOOL',
        'PERSONALIZATION',
        'PRODUCTIVITY',
        'PARENTING',
        'WEATHER',
        'VIDEO_PLAYERS',
        'NEWS_AND_MAGAZINES',
        'MAPS_AND_NAVIGATION',
    ],
  },
  {
      column_name: 'App',
      label: 'Name',
      filter_type: 'Input'
  }
];
